name: 'Go Test Action'
description: 'Run `go test` with rich summary output and annotations.'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  moduleDirectory:
    description: 'Directory of go module to test'
    required: false
    default: '.'
  testArguments:
    description: 'Arguments to `go test`, `-json` will be prepended'
    required: false
    default: './...'
  omitUntestedPackages:
    description: 'Omit any packages from summary output that do not have tests'
    required: false
    default: 'false'
  omitPie:
    description: 'Omit the pie chart from the summary output'
    required: false
    default: 'false'
  fromJSONFile:
    description: 'Parse the specified JSON file, instead of executing go test'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
