name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: check dist
      run: |
        changed_files_count=$(git status --porcelain | wc -l)
        if [ $changed_files_count -ne 0 ]; then
          echo 'mismatched files from ncc generation! did you forget to run `npm run build`?' | tee -a $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
